üëãüõ≥Ô∏è Ahoy, welcome to Kaggle! You‚Äôre in the right place.
This is the legendary Titanic ML competition ‚Äì the best, first challenge for you to dive into ML competitions and familiarize yourself with how the Kaggle platform works.

If you want to talk with other users about this competition, come join our Discord! We've got channels for competitions, job postings and career discussions, resources, and socializing with your fellow data scientists. Follow the link here: https://discord.gg/kaggle

The competition is simple: use machine learning to create a model that predicts which passengers survived the Titanic shipwreck.

Read on or watch the video below to explore more details. Once you‚Äôre ready to start competing, click on the "Join Competition button to create an account and gain access to the competition data. Then check out Alexis Cook‚Äôs Titanic Tutorial that walks you through step by step how to make your first submission!

In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

# Leer los datos
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
# Seleccionar features simples para empezar
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']
X_train = train[features]
y_train = train['Survived']

print(X_train.head(10))
print(y_train.head(10))

   Pclass     Sex   Age  SibSp  Parch     Fare
0       3    male  22.0      1      0   7.2500
1       1  female  38.0      1      0  71.2833
2       3  female  26.0      0      0   7.9250
3       1  female  35.0      1      0  53.1000
4       3    male  35.0      0      0   8.0500
5       3    male   NaN      0      0   8.4583
6       1    male  54.0      0      0  51.8625
7       3    male   2.0      3      1  21.0750
8       3  female  27.0      0      2  11.1333
9       2  female  14.0      1      0  30.0708
0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: Survived, dtype: int64

In [8]:
# Procesamiento b√°sico: convertir sexo a num√©rico y completar nulos
X_train['Sex'] = X_train['Sex'].map({'male': 0, 'female': 1})
X_train['Age'].fillna(X_train['Age'].median(), inplace=True)
X_train['Fare'].fillna(X_train['Fare'].median(), inplace=True)

X_test = test[features]
X_test['Sex'] = X_test['Sex'].map({'male': 0, 'female': 1})
X_test['Age'].fillna(X_test['Age'].median(), inplace=True)
X_test['Fare'].fillna(X_test['Fare'].median(), inplace=True)

print(X_test.head(10))

   Pclass  Sex   Age  SibSp  Parch     Fare
0       3    0  34.5      0      0   7.8292
1       3    1  47.0      1      0   7.0000
2       2    0  62.0      0      0   9.6875
3       3    0  27.0      0      0   8.6625
4       3    1  22.0      1      1  12.2875
5       3    0  14.0      0      0   9.2250
6       3    1  30.0      0      0   7.6292
7       2    0  26.0      1      1  29.0000
8       3    1  18.0      0      0   7.2292
9       3    0  21.0      2      0  24.1500

/tmp/ipykernel_19/1599901580.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Sex'] = X_train['Sex'].map({'male': 0, 'female': 1})
/tmp/ipykernel_19/1599901580.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train['Age'].fillna(X_train['Age'].median(), inplace=True)
/tmp/ipykernel_19/1599901580.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Age'].fillna(X_train['Age'].median(), inplace=True)
/tmp/ipykernel_19/1599901580.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train['Fare'].fillna(X_train['Fare'].median(), inplace=True)
/tmp/ipykernel_19/1599901580.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Fare'].fillna(X_train['Fare'].median(), inplace=True)
/tmp/ipykernel_19/1599901580.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['Sex'] = X_test['Sex'].map({'male': 0, 'female': 1})
/tmp/ipykernel_19/1599901580.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test['Age'].fillna(X_test['Age'].median(), inplace=True)
/tmp/ipykernel_19/1599901580.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['Age'].fillna(X_test['Age'].median(), inplace=True)
/tmp/ipykernel_19/1599901580.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test['Fare'].fillna(X_test['Fare'].median(), inplace=True)
/tmp/ipykernel_19/1599901580.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['Fare'].fillna(X_test['Fare'].median(), inplace=True)

In [ ]:
# Entrenar modelo sencillo
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Predecir para test
predictions = model.predict(X_test)

# Crear archivo submission.csv
submission = pd.DataFrame({
    'PassengerId': test['PassengerId'],
    'Survived': predictions
})
submission.to_csv('submission.csv', index=False)